# Use "name" and "version" from package.json as a Docker material.
APP_NAME=$(grep '"name"' package.json | sed -E 's/.*"name": *"([^"]+)".*/\1/')
VERSION=$(grep '"version"' package.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')
GITHUB_REPOSITORY_OWNER_USERNAME=$(git config user.name)
IMAGE_ID="$APP_NAME:$VERSION"

# Update modules
pnpm install

# Delete existing container
echo "Container '$APP_NAME' exists. Deleting."
docker rm -f "$APP_NAME"

# Pull Docker image generated by GitHub Actions
IMAGE_URL="ghcr.io/$GITHUB_REPOSITORY_OWNER_USERNAME/$IMAGE_ID"
docker pull $IMAGE_URL

# Get the Dotenv key
DOTENV_PRODUCTION_KEY=$(pnpm dlx dotenv-vault@latest keys production | tail -n 1)

# Build the container
docker create --network=host -e DOTENV_KEY="$DOTENV_PRODUCTION_KEY" --name $APP_NAME $IMAGE_URL

# Start the container
docker start $APP_NAME

# Success message
echo "Container created under the name, $APP_NAME"