# Use "name" and "version" from package.json as a Docker material.
APP_NAME=$(grep '"name"' package.json | sed -E 's/.*"name": *"([^"]+)".*/\1/')
VERSION=$(grep '"version"' package.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')
GITHUB_REPOSITORY_OWNER_USERNAME=$(git config user.name)
IMAGE_ID="$APP_NAME:$VERSION"

# Update modules
pnpm install

# Delete existing container
echo "Container '$APP_NAME' exists. Deleting."
docker rm -f "$APP_NAME"

# Pull Docker image generated by GitHub Actions
docker pull ghcr.io/${GITHUB_REPOSITORY_OWNER_USERNAME}/${IMAGE_ID}

# Build the container
docker create --name $APP_NAME $IMAGE_ID

# Start the container
docker start $APP_NAME

# Success message
echo "Container created under the name, $APP_NAME"