name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  push:
    name: Build Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest version from package.json
        id: latest-project-version
        run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Compare versions before building image
        id: "project-version-comparison"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREV_COMMIT_SHA=${{ github.event.before }}

          PREV_VERSION=$(git show $PREV_COMMIT_SHA:package.json | jq -r '.version')
          CURR_VERSION=${{ steps.latest-project-version.outputs.version }}

          echo "Previous/Current version: v$PREV_VERSION | v$CURR_VERSION"

          if [ "$PREV_VERSION" == "$CURR_VERSION" ]; then
            echo "No version change detected. Build skipped."

            echo "skip_build=true" >> $GITHUB_OUTPUT
          fi

      - name: Set repository variable
        if: steps.project-version-comparison.outputs.skip_build != 'true'
        id: lower-repo
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{steps.lower-repo.outputs.repository}}:${{steps.latest-project-version.outputs.version}}
            ghcr.io/${{steps.lower-repo.outputs.repository}}:latest
